"""Add game_mode to Riddle model

Revision ID: 1358e899cec4
Revises: 71c9984c5eca
Create Date: 2025-05-05 23:49:19.792312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1358e899cec4'
down_revision = '71c9984c5eca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('riddle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_mode', sa.String(length=50), server_default='Classic', nullable=True))
        batch_op.drop_index('ix_riddle_day_number')
        batch_op.create_index('ix_riddle_game_mode_day_number', ['game_mode', 'day_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('riddle', schema=None) as batch_op:
        batch_op.drop_index('ix_riddle_game_mode_day_number')
        batch_op.create_index('ix_riddle_day_number', ['day_number'], unique=1)
        batch_op.drop_column('game_mode')

    # ### end Alembic commands ###
