"""Add PlayerStats model

Revision ID: 6443e7c48233
Revises: b962fd4f44ab
Create Date: 2025-05-04 19:30:51.770522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6443e7c48233'
down_revision = 'b962fd4f44ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_stats',
    sa.Column('player_uuid', sa.String(length=36), nullable=False),
    sa.Column('total_games', sa.Integer(), nullable=False),
    sa.Column('total_incorrect', sa.Integer(), nullable=False),
    sa.Column('current_play_streak', sa.Integer(), nullable=False),
    sa.Column('longest_play_streak', sa.Integer(), nullable=False),
    sa.Column('current_correct_streak', sa.Integer(), nullable=False),
    sa.Column('longest_correct_streak', sa.Integer(), nullable=False),
    sa.Column('last_played_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('player_uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_stats')
    # ### end Alembic commands ###
