"""Initial migration with Riddle model

Revision ID: 7a52c7c080db
Revises: 
Create Date: 2025-05-04 13:21:55.327506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a52c7c080db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('riddle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emojis', sa.String(length=100), nullable=False),
    sa.Column('answer', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('emojis')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('riddle')
    # ### end Alembic commands ###
