"""Remove unique constraint on emoji per game_mode

Revision ID: a6607aae6f3c
Revises: 56f793c31572
Create Date: 2025-05-06 21:03:48.870381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6607aae6f3c'
down_revision = '56f793c31572'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('riddle', schema=None) as batch_op:
        batch_op.drop_constraint('uq_emoji_game_mode', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('riddle', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_emoji_game_mode', ['emoji', 'game_mode'])

    # ### end Alembic commands ###
